from __future__ import annotations

from typing import Protocol


class SessionStore(Protocol):
    def mint(self) -> str: ...

    def get(self, session_id: str) -> list[tuple[str, str]]: ...

    def append(self, session_id: str, role: str, content: str) -> None: ...

    def expire(self) -> None: ...

    def clear(self, session_id: str) -> None: ...
